server:
  port: 8485

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
  health:
    mail:
      enabled: false

idam:
  s2s-auth:
    url: ${S2S_URL}

# liveness alert settings depend on application name, if it is changed alert configuration must also be adjusted
# https://github.com/hmcts/bulk-scan-shared-infrastructure/blob/master/liveness-alert.tf
spring:
  application:
    name: Send Letter Service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${LETTER_TRACKING_DB_HOST:send-letter-database}:${LETTER_TRACKING_DB_PORT:5432}/${LETTER_TRACKING_DB_NAME:letter_tracking}${LETTER_TRACKING_DB_CONN_OPTIONS:}
    username: ${LETTER_TRACKING_DB_USER_NAME:letterservice}
    password: ${LETTER_TRACKING_DB_PASSWORD:}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 30
      idleTimeout: 10000
      poolName: SendLetterHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

reports:
  upload-summary:
    cron: ${UPLOAD_SUMMARY_REPORT_CRON:0 0 19 * * *}
    enabled: ${UPLOAD_SUMMARY_REPORT_ENABLED:false}
    recipients: ${UPLOAD_SUMMARY_REPORT_RECIPIENTS:}
  service-config:
    - service: cmc_claim_store
      display-name: CMC
    - service: send_letter_tests
      display-name: Bulk Print
    - service: divorce_frontend
      display-name: Divorce
    - service: probate_backend
      display-name: Probate
    - service: sscs
      display-name: SSCS
    - service: finrem_document_generator
      display-name: FINREM
    - service: fpl_case_service
      display-name: FPLA
  delayed-stale-report:
    cron: ${DELAYED_STALE_REPORT_CRON:0 0 9 * * 5}
    enabled: ${DELAYED_STALE_REPORT_ENABLED:false}
    recipients: ${DELAYED_STALE_REPORT_RECIPIENTS:}

flyway:
  user: ${LETTER_TRACKING_DB_USER_NAME}
  password: ${LETTER_TRACKING_DB_PASSWORD}
ftp:
  hostname: ${FTP_HOSTNAME}
  port: ${FTP_PORT}
  target-folder: ${FTP_TARGET_FOLDER}
  smoke-test-target-folder: ${FTP_SMOKE_TEST_TARGET_FOLDER:SMOKE_TEST}
  reports-folder: ${FTP_REPORTS_FOLDER}
  reports-cron: ${FTP_REPORTS_CRON:0 30 0 * * *}
  fingerprint: ${FTP_FINGERPRINT}
  username: ${FTP_USER}
  privateKey: ${FTP_PRIVATE_KEY}
  publicKey: ${FTP_PUBLIC_KEY}
  downtime:
    from: ${FTP_DOWNTIME_FROM:16:00}
    to: ${FTP_DOWNTIME_TO:17:00}
    disableDowntime: ${FTP_disableDowntime:false}
  service-folders:
    - service: cmc_claim_store
      folder: CMC
    - service: send_letter_tests
      folder: BULKPRINT
    - service: nfdiv_cos
      folder: DIVORCE
    - service: divorce_frontend
      folder: DIVORCE
    - service: probate_backend
      folder: PROBATE
    - service: sscs
      folder: SSCS
    - service: finrem_document_generator
      folder: FINREM
    - service: fpl_case_service
      folder: FPL

scheduling:
  enabled: ${SCHEDULING_ENABLED:false}
  lock_at_most_for: ${SCHEDULING_LOCK_AT_MOST_FOR:PT10M} # 10 minutes in ISO-8601

tasks:
  upload-letters:
    interval-ms: ${UPLOAD_LETTERS_INTERVAL:30000}
    db-poll-delay: ${DB_POLL_DELAY:2}
  mark-letters-posted:
    cron:  ${FTP_REPORTS_CRON:0 30 * * * *}
  stale-letters-report:
    cron: ${STALE_LETTERS_REPORT_CRON:0 30 11 * * *}
  pending-letters-report:
    cron: ${PENDING_LETTERS_REPORT_CRON:0 0 9 * * *}
    before-mins: ${PENDING_LETTERS_BEFORE:15}

file-cleanup:
  enabled: ${FILE_CLEANUP_ENABLED:false}
  cron: ${FILE_CLEANUP_CRON:0 15 * * * *}
  ttl: 12h

old-letter-content-cleanup:
  enabled: ${OLD_LETTER_CONTENT_CLEANUP_ENABLED:false}
  cron: ${OLD_LETTER_CONTENT_CLEANUP_CRON:0 0 7 * * *}
  ttl: P31D

encryption:
  enabled: ${ENCRYPTION_ENABLED:false}
  publicKey: ${ENCRYPTION_PUBLIC_KEY:}

stale-letters:
  min-age-in-business-days: 2

async:
  threadpool-size: ${ASYNC_THREADPOOL_SIZE:20}

file-upoad:
  retries: ${DEFAULT_RETRIES:5}
  wait-time-in-ms: ${DEFAULT_WAIT_TIME_IN_MS:2000}

