name: rpe-send-letter-service
apiVersion: v2
home: https://github.com/hmcts/send-letter-service
version: 0.1.3
description: HMCTS Send letter service
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
dependencies:
  - name: java
    version: ~3.0.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
